[클린코드 6기 박찬우] 영화 리뷰 미션 STEP 1
next-step/js-movie-review pull request #9
Opened 2024-05-27 16:48 UTC by chanw9503

안녕하세요 :) 리뷰어님 이번 미션도 잘부탁드립니다.
부족하지만 최선을 다하겠습니다.

## 구현 방식
저는 이번 개발을 할 때 Top-Down 방식을 사용했습니다. Bottom-Up 방식으로 하나씩 쌓아 올려보려 했으나, 처음에 어떻게 나누고 개발해야 할지 갈팡질팡해서, 구현을 먼저 해보고 나누자는 생각으로 진행했습니다. 처음 진행한 내용은 webpack, ESLint, Prettier 등의 환경 설정이었습니다. 그 후 TMDB 호출이 정상적으로 이루어지는지 확인하고, 해당 내용을 구현했습니다. 이후 불러온 영화 정보를 렌더링해주는 부분을 개발하고, 작은 부분으로 리팩토링했습니다.

## 궁금한 점
1. JS로 컴포넌트를 만든다고 했을 때, 제가 구현한 방법은 renderHeader.js 파일명으로 각각 만들고, querySelector나 getElementById로 호출해서 해당 내용에 innerHTML이나 innerText로 값을 넣었는데, 이런 식으로 만드는 게 컴포넌트라고 정의할 수 있을까요?

2. 비동기에 대한 에러 핸들링 부분이 아직 많이 미숙한 것 같습니다. 제가 구현한 부분에서 이상한 점이나 미숙한 부분이 있는지 확인 부탁드립니다. TMDB에서 에러가 발생했을 경우 조건문으로 에러를 감지하고 throw Error를 발생시켜 함수 호출한 부분에서 모달로 에러 내용을 띄우도록 구현했는데, 이 방법이 맞는지 모르겠습니다. try/catch의 catch 부분에서 에러를 감지해 넘기는 게 맞다고 생각했으나, 이 부분에서 에러가 감지되지 않는 것 같았습니다. 그래서 이렇게 구현했는데, 맞을까요?

3. 제가 이번에 Cinema와 Movies를 클래스로 구현했는데, 클래스 구현 이유는 다음과 같습니다. Movie 클래스는 영화 정보에 대한 명시화를 위해, 즉 서버에서 받은 데이터가 어떤 것인지 명확히 하기 위해 생성했습니다. Cinema 클래스는 영화 정보를 받고 화면에 그려주는 객체가 있으면 재사용하기 편하겠다는 생각에서 만들었습니다. 객체에 대해서 아직은 많이 어색한데 이런식으로 활용하는게 맞을지에 대해 질문드립니다.

2024-05-29 16:39 UTC, JunilHwang requested changes
안녕하세요 찬우님!
영화 리뷰 미션을 함께하게 된 리뷰어 황준일입니다 🙏
일단 리뷰가 늦어져서 죄송합니다 ㅠㅠ 다음엔 빠르게 리뷰 남겨보겠습니다..!

전체적인 피드백을 정리해보면 다음과 같습니다.

### 1. 에러처리

1. API에서 오류가 발생
2. API 호출 함수에서 바로 catch하여 console.error를 띄움
3. API를 사용하는 입장에서는 에러가 발생해도 전파되지 않기 때문에 어떤 에러가 발생했는지 알 수 없음

3번이 제일 문제입니다. UI까지 error가 전파되지 않기 때문에 error에 대한 다양한 코드가 지금은 무의미하다고 볼 수 있겠네요.

어떤식으로 개선을 해야 좋을지 고민이 필요해보입니다!

### 2. 불필요한 과정이 많음

지금은 class를 사용하기 위한 코드들이 무척 많이 보이는데요,

1. instance를 만들고
2. setter를 실행하고
3. method를 실행하고

1~3을 그냥 하나의 함수로 묶으면(method에 렌더링에 필요한 인자를 넘기면) 더 심플하지 않을까요?

지금은 합리적인 코드라기보단 class를 사용하기 위해 만들어진 코드 처럼 보여요. "왜 이렇게 해야하지?" 라는 의문이 생긴달까..

---

그리고 질문에 대한 답변을 드리자면,

> JS로 컴포넌트를 만든다고 했을 때, 제가 구현한 방법은 renderHeader.js 파일명으로 각각 만들고, querySelector나 getElementById로 호출해서 해당 내용에 innerHTML이나 innerText로 값을 넣었는데, 이런 식으로 만드는 게 컴포넌트라고 정의할 수 있을까요?

재사용 가능하면 컴포넌트이지 않을까요 ㅎㅎ?
특정 ID에 대한 값(getElementById를 내부에서 실행)에 의존성이 있다면 컴포넌트라고 보기 어려울 것 같아요.
element에 대한 정보를 바깥에서 인자로 넘겨주면 어떨까요?

> 비동기에 대한 에러 핸들링 부분이 아직 많이 미숙한 것 같습니다. 제가 구현한 부분에서 이상한 점이나 미숙한 부분이 있는지 확인 부탁드립니다. TMDB에서 에러가 발생했을 경우 조건문으로 에러를 감지하고 throw Error를 발생시켜 함수 호출한 부분에서 모달로 에러 내용을 띄우도록 구현했는데, 이 방법이 맞는지 모르겠습니다. try/catch의 catch 부분에서 에러를 감지해 넘기는 게 맞다고 생각했으나, 이 부분에서 에러가 감지되지 않는 것 같았습니다. 그래서 이렇게 구현했는데, 맞을까요?

이미 질문을 남겨주셨었군요. 에러에 대한 코멘트가 많아서, 따로 여기에 적진 않겠습니다!

> 제가 이번에 Cinema와 Movies를 클래스로 구현했는데, 클래스 구현 이유는 다음과 같습니다. Movie 클래스는 영화 정보에 대한 명시화를 위해, 즉 서버에서 받은 데이터가 어떤 것인지 명확히 하기 위해 생성했습니다. Cinema 클래스는 영화 정보를 받고 화면에 그려주는 객체가 있으면 재사용하기 편하겠다는 생각에서 만들었습니다. 객체에 대해서 아직은 많이 어색한데 이런식으로 활용하는게 맞을지에 대해 질문드립니다.

"서버에서 받은 데이터가 어떤 것인지 명확히 하기 위해 생성했습니다." 이런 목적이라면 괜찮다고 생각합니다. 다만 이걸 domain이라고 보긴 어려울 것 같아요. 
아예 api를 호출하는 함수가 변환하는 역할까지 해주면 어떨까 싶어요. 혹은 api 호출 함수 + 변환 함수를 묶은 하나의 함수를 더 만들어서 사용한다거나?

실무에서는 [zod](https://zod.dev/) 같은 라이브러리를 사용해서 검증하기도 한답니다! 혹은 아예 typescript를 사용하기도 하고, 아니면 jsdoc으로 type을 정의해서 사용하는 방법도 있어요 ㅎㅎ

어쨌든 목적에는 부합하지만 설계에 대한 관점으로 봤을 때 고민해볼 부분은 있습니다.

1. 도메인의 역할은 무엇인가.
2. 컴포넌트는 어떤 영역까지 책임져야 하는가.
3. 변환을 어떤 영역에서 할 것인가

한 번 고민해보세요!

2024-05-29 16:39 UTC, JunilHwang commented on src/apis/getMovieList.js
> +}
API에서 발생한 에러가 바깥으로 전파되어야 UI에서 오류에 대한 정상적인 처리가 가능하지 않을까요?

2024-05-29 16:39 UTC, JunilHwang commented on src/apis/getMovieList.js
> +    }
가령, 여기서 throw를 해봤자 바로 catch가 되기 때문에 throw를 하는 의미가 아예 없답니다!

2024-05-29 16:39 UTC, JunilHwang commented on src/apis/getMovieList.js
> +        url.search = new URLSearchParams(params).toString();
getSerachedMovies 에서도 똑같이 쓰이고 있어서, 이를 추상화한 함수가 하나 있으면 좋지 않을까 싶어요!

2024-05-29 16:39 UTC, JunilHwang commented on src/apis/getSearchedMovies.js
> +    }
앞선 리뷰와 동일합니다

2024-05-29 16:39 UTC, JunilHwang commented on src/apis/getSearchedMovies.js
> +const BASE_URL = 'https://api.themoviedb.org/3/search/movie';
`https://api.themoviedb.org/3`의 경우 getMoveList에서도 동일하게 쓰이고 있어서, 공통 상수로 하나 만들어주면 어떨까 싶어요!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/domain/error.js
> +}
이게 도메인의 영역일까요?
api를 처리하는 부분에 있어야 하는게 아닐까요?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/domain/movie.js
> +}
이 Movie class의 존재이유가 있을까요?
메소드도 getter밖에 없어서 그냥 json data를 그대로 사용해도 무방하지 않나 싶어요!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +export class Cinema {
파일 이름과 클래스 이름은 일치시켜주면 어떨까요~?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +    #skeletonWrapper = document.querySelector('.skeleton-list');
element는 하나의 namespace로 묶어주면 좋을 것 같아요!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +        this.#moviesWrapper.innerHTML += newItemsHTML;
```suggestion
        const newItemsHTML = this.#movies
            .map((movieInfo) => `
              <li>
                <a href="#">
                  <div class="item-card">
                    <img
                      class="item-thumbnail"
                      src="${IMAGE_BASE_URL}${movieInfo.getPosterPath()}"
                      loading="lazy"
                      alt="${movieInfo.title}"
                    />
                    <p class="item-title">${movieInfo.getTitle()}</p>
                    <p class="item-score">
                    ${movieInfo.getVoteAverage()} <img src="${starFilled}" alt="별점" /> 
                    </p>
                  </div>
                </a>
              </li>
            `
            ).join('');
        this.#moviesWrapper.innerHTML += newItemsHTML;
```
return문은 제거해도 무방해보이네요!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +        this.#moviesWrapper.innerHTML += newItemsHTML;
`innerHTML +=` 을 하게 되면 결국 전체적으로 렌더링이 발생하게 되기 때문에 차라리 element로 만들어서 append를 해주면 어떨까요~?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +    }
https://github.com/next-step/js-movie-review/assets/18749057/254f17b5-4d35-4ab3-9fba-9ac881c6e07d

스켈레톤의 위치랑 실제 UI의 위치가 달라서 흔들거리는 모습이 보여요!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +          </li>`
뭔가 변수를 받아서 처리하는건 아니라서, 이 문자열 자체를 상수로 만들어서 관리해주면 좋겠네요!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +    }
```suggestion
    get #skeletonTemplate() {
       const template = `            
          <li>
            <a href="#">
              <div class="item-card">
                <div class="item-thumbnail skeleton"></div>
                <div class="item-title skeleton"></div>
                <div class="item-score skeleton"></div>
              </div>
            </a>
          </li>
        `.trim();
       return Array(flag ? 20 : 0).fill(template);
    }
    
    showSkeleton(flag) {
        this.#skeletonWrapper.innerHTML = this.#skeletonTemplate;
    }
```

이러면 더 심플해지지않나요~?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/view/cinema.js
> +    showMovies() {
set이랑 show를 따로 분리할 필요가 있나요~?

`showMovies(movies)`
이렇게 쓰인다고 생각하면 어떨까요?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/index.js
> +        const itemList = await getMovieList(pages);
앞선 리뷰들의 연장선인데,
여기서 오류가 발생하는 원인이 조금 달라요
getMoveList에서 오류가 발생해도 오류는 전파되지 않아요.
왜냐면 내부에서 이미 catch를 하고 있기 때문이죠.

그럼 여기서 발생할 수 있는 오류는 moveList가 console.error을 했을 때, return 값이 undefined이고
itemList에는 undefined가 들어가고
뒤에 있는 로직들이 정상적으로 실행되지 않는거죠

그럼 이 때 이 renderMovieItems 함수에서 알 수 있는 오류의 정보랑 기대하는 오류의 정보가 완전 달라지게 된답니다!

2024-05-29 16:39 UTC, JunilHwang commented on src/js/index.js
> +            cinema.showMovies();
```suggestion
            cinema.showMovies(itemList.results);
```
그냥 이렇게 표현해버리면 어떨까요?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/index.js
> +addEventListener('DOMContentLoaded', () => {
오호.. 그냥 이렇게 addEventListener 만 호출할 수도 있군요.
처음 알았네요

2024-05-29 16:39 UTC, JunilHwang commented on src/js/index.js
> +async function renderMovieItems(pages) {
이 함수도 별도의 파일로 분리되어야 하지 않을까 싶네요!
아마 api와의 의존성을 끊어내고 싶으셨던 것 같은데,

```js
renderMovieItems(await getMovieList(pages));
```
이런식으로 바깥에서 api에 대한 응답 값만 넘겨주도록 만들면 어떨까요?

2024-05-29 16:39 UTC, JunilHwang commented on src/js/index.js
> +    });
모달을 띄우는 부분을 함수로 만들어서 사용할 수 있을 것 같아요

2024-05-29 16:39 UTC, JunilHwang commented on src/js/index.js
> +    });
그리고 에러에 대한 피드백은 앞선 내용과 동일합니다.

2024-05-29 16:39 UTC, JunilHwang commented on cypress/e2e/movie/movie.cy.js
> +    });
API의 응답 결과에 대한 렌더링된 모습에 대해 비교하는 방법도 있답니다..!

현재: 결과가 나오는지만 확인 가능
개선: API의 응답을 모킹해서 사용하면, 결과에 대해 어떤 모습으로 렌더링이 되는지까지 유추 가능

2024-06-02 08:05 UTC, chanw9503 commented on src/apis/getMovieList.js
> +}
네 맞습니다!!ㅠㅠ getMoviewList에서는 try/catch문을 삭제했고 에러를 throw하는 방법도 조금더 간소화 해보기위해 
then을 사용해서 res.json()으로 얻은 본문의 결과에서 success 실패시 에러를 throw하고 아닐경우 결과값을 린턴하고도록
변경해봤습니다. 그리고 Error를 Custom 해서 작생해봤는데요!! code라는 값도 리턴하면 좋을거 같아서 기존에 있던
Error contstuctor를 상속받고 추가적으로 code라는 변수를 추가했습니다!

2024-06-02 08:21 UTC, chanw9503 commented on src/apis/getMovieList.js
> +    }
넵!! 수정하겠습니다 :) 감사합니다

2024-06-02 08:26 UTC, chanw9503 commented on src/apis/getMovieList.js
> +        url.search = new URLSearchParams(params).toString();
createUrlSeacrhParams라는 함수를 만들어서, BaselUrl, params를 매개변수로 받는 함수로 만들어봤습니다!!

2024-06-02 08:27 UTC, chanw9503 commented on src/apis/getSearchedMovies.js
> +    }
넵!! 에러를 이곳에서 다루는게 아니라, UI를 다루는 곳에서 try/catch 할수 있도록 수정하겠습니다.

2024-06-02 08:36 UTC, chanw9503 commented on src/apis/getSearchedMovies.js
> +const BASE_URL = 'https://api.themoviedb.org/3/search/movie';
공통상수로 만들어 사용하는게, 좋을거같습니다.  BASE_URL에 수정이 발생하면 한번에 모든 내용르 바꾸기에 그게 더 좋은 방법인거 같습니다 .!!

2024-06-02 09:27 UTC, chanw9503 commented on src/js/domain/error.js
> +}
도메인 영역보다는 apis의 utils함수로 사용하는 것이 좋을꺼같습니다!!

2024-06-02 09:27 UTC, chanw9503 commented on src/js/view/cinema.js
> +export class Cinema {
넵!! 변경하겠습니다.

2024-06-02 14:12 UTC, chanw9503 commented on src/js/view/cinema.js
> +    #skeletonWrapper = document.querySelector('.skeleton-list');
element라는 이름의 객체로 묶었고, Wrapper라는 표현보다 List라는 표현으로 변경해봤습니다!

2024-06-02 15:04 UTC, chanw9503 commented on src/js/view/cinema.js
> +        this.#moviesWrapper.innerHTML += newItemsHTML;
그거까지는 생각하지 못했던거 같습니다!! 말씀해주신 내용을 바탕으로 수정해보겠습니다.

2024-06-07 13:17 UTC, chanw9503 commented
안녕하세요 리뷰어님!! 수정이 늦었습니다. 죄송합니다 ㅠㅠ 
리뷰어님이 피드백 주신 내용 확인후에, 제 코드를 다시 확인하면서 변경해야될 내용을 파악했습니다.

제가 접근방식이 잘못되었다는것을 깨닫고 전체적으로 다시한번 수정해봤습니다. :)


### API 비동기 처리 
이번 수업을 통해서 공부하게된 내용을 적용해봤습니다. Fetch에 대한 래핑객체를 생성했습니다.
래핑객체로 묶을 때 좋다고 생각한점은 변경의 최소화였습니다. 아무래도 호출관련, 예외처리 관련내용을 
래핑객체 안에서 처리를하다보니 다른 라이브러리로 바꾼다고 했을때 변경을 최소화할 수 있겠다라고 느껴지는거 같습니다.

### 도메인의 삭제
도메인에 대해서도 고민을 많이 해봤는데요. 아직까지는 막 와닫는 부분이 없는거같습니다. 
강의를 통해서 배운내용은 이번에 호출하는 곳이 TMDB이지만 다른 곳에서도 다른 영화 정보를 호출한다고 했을때,
그곳과 TMDB의 API 호출 response값이 다를거고, 그렇기에 각각의 호출 주체에 맞게 생성하는것이 도메인이고
도메인만 변경함으로써 손쉽게 다른 정보를 가져올 수 있다?? 이런식으로 배우긴했는데 조금더 공부가 필요할거같습니다!!

### 컴포넌트의 정리
컴포넌트들을 분리해봤습니다. document.createElement를 생성해서 각각의 엘리먼트를 생성해 클래스를 주입하는
방식을 사용했습니다. 이렇게 하니 확실히 의존성을 줄일 수 있다는 생각 들었습니다. 


### 궁금한점
index.js나 Cinema.js에서 이벤트 관련 메서드(addEventListener)를 사용했는데요. 이런것들은 어떻게
관리하면 좋을까요? 이부분이 궁금합니다.

2024-06-08 07:40 UTC, JunilHwang approved these changes
안녕하세요 찬우님~
리뷰 반영 잘 해주셨네요!

### 1. 컴포넌트

일단 컴포넌트가 외부 의존을 최소화하긴 했는데, 전부다 DOM 기반으로 작성되어 있어서 변경사항이 발생하면 코드를 이해하고 수정하는데 시간이 무척 오래걸릴 것 같아요!
무엇보다 어딘가에서는 클래스를 작성하고 어딘가에선 함수로 작성되어있다보니, 쉽게 말해서 코드가 어떤 모습으로 존재하거나 동작할지에 대한 예측이 잘 안 되는 상황입니다.

그래서 코드를 작성할 때에는 일관성이 중요해요!

### 2. API 관리

결국 try 내부에서 Throw를 하고, 이걸 다시 catch에서 또 throw를 해주고 있어요.
그래서 try~catch에서 발생시킨 error는 쓸모가 없어진 상황입니다 ㅎㅎ
그 에러 정보를 바깥에선 절대 알 수 없어요. 무조건 똑같은 에러만 전달되는거죠.

fetch나 axios가 기본적으로 제공하는 에러들이 있는데, 이걸 잘 정제해서 활용해야 훨씬 효과적이지 않을까요? 지금은 바깥에 전달하는 정보를 아예 차단시키기 때문에 유의미한 에러로 쓰일 일이 거의 없네요..

### 3. DOMContentLoaded

index.js에 app에 대해 domcontentloaded 이벤트를 실행시키려고 한 것 같은데, 이 이벤트가 정확히 어떤 이벤트인지 살펴보셔야할 것 같아요! 자세한건 상세 리뷰를 확인해주세요~

### 4. 테스트 케이스

테스트를 작성할 때 극단적인 상황도 조금씩 생각해보시면 좋답니다 ㅎㅎ
지금은 스켈레톤과 관련된 부분이 찬우님이 예상한거랑 다르게 동작할 확률이 높아보이네요!

---

그리고 질문에 대한 답변을 드리자면...

> index.js나 Cinema.js에서 이벤트 관련 메서드(addEventListener)를 사용했는데요. 이런것들은 어떻게 관리하면 좋을까요? 이부분이 궁금합니다.

사실 질문이 모호해요. "어떻게 관리하면 좋을까요?" 에서 불편한 지점을 더 구체적으로 이야기 해주시면 좋을 것 같습니다. 지금은 컴포넌트 내부에 ( 가령 Button 이라거나... ) `onClick` 같은 이벤트를 정의해주시긴 했는데... 이런게 제대로 활용되고 있지 못한 것 같네요!
정의를 해준김에, 활용을 해보면 어떨까 싶어요!

---

일단 이번 단계는 여기서 마무리하도록 하겠습니다!
다음 단계 진행하면서 참고해주세요~
조금만 더 힘내봅시다!!

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +    }
멤버변수는 클래스 필드에 미리 정의해주세요!

```suggestion
export class Cinema {
    isConnect;
    page;
    movieListElement;
    
    constructor() {
        this.isConnect = false;
        this.page = 1;
        this.movieListElement = document.querySelector('.item-list');
    }
```

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +        this.isConnect = false;
```js
const isArray = Array.isArray({})
```

is를 변수의 prefix에 사용하게 되면 위와같이 매~~~~~~~~~~~우 헷갈리는 상황이 벌어질 수 있답니다 ㅎㅎ

2024-06-08 07:40 UTC, JunilHwang commented on src/index.js
> +app.addEventListener('DOMContentLoaded', MovieListView());
이 부분이 무척 이상하네요 ㅎㅎ

MoveListView는 함수이고, 반환값은 undefined 입니다.
즉, 이 코드는 DOMContentLoaded 가 발생하는 시점에 실행되는 함수가 아니라
그냥 함수를 실행해서 undefined를 addEventListener에게 반환하는 형태입니다.

의도한 동작과는 아예 다른거죠.

```suggestion
app.addEventListener('DOMContentLoaded', MovieListView);
```

그래서 이렇게 해야 하지 않을까요?

2024-06-08 07:40 UTC, JunilHwang commented on src/index.js
> +app.addEventListener('DOMContentLoaded', MovieListView());
```suggestion
app.appendChild(Layout());
MovieListView();
```

그런데 이렇게 작성하는거랑 어떤 차이가 있을까요?
두 번째로, app에 대해서 DOMContentLoaded 이벤트가 발생하긴 할까요?

발생하지 않는다면 그 이유는 무엇일까요?

2024-06-08 07:40 UTC, JunilHwang commented on src/view/MovieListView.js
> +
이 코드를 봤을 때 드는 생각들입니다.

1. more-movies가 어디에 있는걸까?
2. moreButton을 눌렀을 때 cinema 내부의 값(page)을 올리는데, 이게 사실 MovieListView 가 가지고 있어야 하는 값이 아닐까? 
3. Cinema랑 MoveList랑 어떤 차이인걸까? 용어가 무척 헷갈린다.
    - cinema : 영화
    - MovieList : 영화 목록
    - CinemaList > ????
    - Moivie > ????

2024-06-08 07:40 UTC, JunilHwang commented on src/view/MovieListView.js
> +            document.querySelector('body').appendChild(modal.rendered);
```suggestion
new Modal(document.querySelector('body'), error.message);
```

이런식으로 표현할 수 있으면 어떨까 싶네요!

2024-06-08 07:40 UTC, JunilHwang commented on src/view/MovieListView.js
> +                document.querySelector('body').appendChild(modal.rendered);
똑같은 코드가 반복적으로 쓰이는군요!

2024-06-08 07:40 UTC, JunilHwang commented on src/view/MovieListView.js
> +                cinema.showSekeleton(20, true);
```suggestion
                cinema.loading();
```
이런식으로 표현할 수 있으면 어떨까 싶기도..
스켈레톤으로 표현하고 있다는걸 외부에서 알아야할 필요가 있을까요~?

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +export class Cinema {
MovieListView는 함수인데 Cinema는 클래스인 이유가 있나요?

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +                src: `${IMAGE_BASE_URL}${movie.poster_path}`,
IMAGE_BASE_URL이 Cinema에서만 쓰이는데 constants 파일에 분리해놓을 필요가 있을까요?

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +                src: `${IMAGE_BASE_URL}${movie.poster_path}`,
저는 코드를 관리할 때 "스코프"가 무척 중요하다고 생각해요.
그 코드의 영향이 가는 범위를 정해놓고, 그 바깥을 벗어나지 않도록 하는거죠 ㅎㅎ
가령 IMAGE_BASE_URL의 영향 범위(스코프)는 Cinema 까지입니다. 그 바깥과는 아무 상관이 없죠.
그렇다면 이 친구들이 같이 뭉쳐있어야 관리하기가 쉽지 않나 싶어요!

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +                src: `${IMAGE_BASE_URL}${movie.poster_path}`,
가령 우리가 함수를 작성할 때

그 함수에서 쓰이는 변수는 그 함수 내부에 정의해서 사용하잖아요?
전부다 함수 바깥에서 정의하지 않는 것 처럼요!

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +        this.movieListElement.appendChild(fragment);
지금 fragment를 활용하는 구간이 꽤 많아보여요.
그렇다면 이런 유틸 함수를 하나 만들어서 관리하면 어떨까 싶네요!

```js
appendFragments(this.moveListElement, Array(count).map(MovieCard));
```

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +        }, 5000);
이 코드의 존재 이유를... 잘 모르겠네요

2024-06-08 07:40 UTC, JunilHwang commented on src/view/Cinema.js
> +        }, 5000);
아마 스켈레톤 UI 의 관리 책임이 분산되어있어서 그런 것 같아요.

2024-06-08 07:40 UTC, JunilHwang commented on src/view/MovieListView.js
> +    });
만약 moreButton을 연속으로 10회 정도 누른다고 가정하면 어떤 일이 발생할까요?

스켈레톤 UI 와 엮어서 생각해보세요!

2024-06-08 07:40 UTC, JunilHwang commented on src/components/Layout.js
> +}
Layout은 fragment를 반환하네요..?

2024-06-08 07:40 UTC, JunilHwang commented on src/apis/apiClient.js
> +        }
`throw new APIError(data.status_code, data.status_message);`

이 부분이 의미있게 쓰일 수 있을까요?

2024-06-08 07:40 UTC, JunilHwang commented on src/apis/apiClient.js
> +        }
그리고 fetch 자체가 제공하는 에러 정보가 훨씬 유용하지 않을까요?

2024-06-08 07:40 UTC, JunilHwang commented on src/apis/utils/createUrlSeachParams.js
> +};
apiClient 에도 있는 코드네요!?

2024-06-08 07:40 UTC, JunilHwang commented on cypress/e2e/MovieList.cy.js
> +    it('홈 화면에서 더보기 버튼을 클릭 시, 영화 리스트 20개가 추가된다.', () => {
더보기 버튼을 연속으로 10번 정도 눌러보는 테스트도 추가해보세요!

2024-06-08 07:41 UTC, merged

2024-06-09 16:23 UTC, chanw9503 commented on src/view/Cinema.js
> +    }
넵!! 클래스 필드에 미리 정의하겠습니다.

2024-06-09 16:39 UTC, chanw9503 commented on src/view/Cinema.js
> +                src: `${IMAGE_BASE_URL}${movie.poster_path}`,
리뷰어님 말씀대로 같이 쓰이는게 좋을거같습니다!!
저는 "상수니까" 분리를 했던거 같습니다. 잘못된 접근 방식이있고 같은 스코프내에 있는 변수는
바깥에 정의하는것 보다 뭉쳐있는것이 관리면에서도 더 좋을거같습니다!

2024-06-09 16:42 UTC, chanw9503 commented on src/view/Cinema.js
> +        this.isConnect = false;
앗...그럴수 있을거같습니다. 새로운 변수명으로 수정해보겠습니다!

2024-06-15 06:35 UTC, chanw9503 commented on src/apis/utils/createUrlSeachParams.js
> +};
중복되는 부분을 삭제했습니다!

2024-06-15 06:42 UTC, chanw9503 commented on src/view/MovieListView.js
> +            document.querySelector('body').appendChild(modal.rendered);
훨씬더 가독성이 좋아진거같습니다...ㅠㅠ 더 간단한게 표현할 수 있는 방법을 생각하도록 하겠습니다!

2024-06-15 07:02 UTC, chanw9503 commented on src/view/Cinema.js
> +        this.movieListElement.appendChild(fragment);
넵!! 유틸함수를 사용해서 더 편하게 관리해보겠습니다

2024-06-15 07:03 UTC, chanw9503 commented on src/view/Cinema.js
> +        }, 5000);
제가 스켈레톤을 잘못사용한거같습니다!!ㅜㅜ 수정하겠습니다

2024-06-15 07:03 UTC, chanw9503 commented on src/components/Layout.js
> +}
수정했습니다!!ㅜ